//
// AuthLoginResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthLoginResponse: Codable {

    public var message: String?
    public var result: Bool?
    public var payload: User?

    public init(message: String? = nil, result: Bool? = nil, payload: User? = nil) {
        self.message = message
        self.result = result
        self.payload = payload
    }


}
