//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var _id: String?
    public var uuid: String?
    public var firstName: String?
    public var lastName: String?
    public var fullName: String?
    public var email: String?
    public var avatarUrl: String?
    public var timezone: String?
    public var countryCode: String?
    public var phone: String?
    public var emailVerifiedAt: String?
    public var phoneVerifiedAt: String?
    public var subscriptionLevel: String?
    public var storeName: String?
    public var isProfileCompleted: Bool?
    public var isPackageSelected: Bool?
    public var isPaymentMethods: Bool?
    public var isSubscribed: Bool?
    public var accessToken: String?
    public var isFree: Bool?

    public init(_id: String?, uuid: String?, firstName: String?, lastName: String?, fullName: String?, email: String?, avatarUrl: String?, timezone: String?, countryCode: String?, phone: String?, emailVerifiedAt: String?, phoneVerifiedAt: String?, subscriptionLevel: String?, storeName: String?, isProfileCompleted: Bool?, isPackageSelected: Bool?, isPaymentMethods: Bool?, isSubscribed: Bool? = nil, isFree: Bool? = nil, accessToken: String?) {
        self._id = _id
        self.uuid = uuid
        self.firstName = firstName
        self.lastName = lastName
        self.fullName = fullName
        self.email = email
        self.avatarUrl = avatarUrl
        self.timezone = timezone
        self.countryCode = countryCode
        self.phone = phone
        self.emailVerifiedAt = emailVerifiedAt
        self.phoneVerifiedAt = phoneVerifiedAt
        self.subscriptionLevel = subscriptionLevel
        self.storeName = storeName
        self.isProfileCompleted = isProfileCompleted
        self.isPackageSelected = isPackageSelected
        self.isPaymentMethods = isPaymentMethods
        self.isSubscribed = isSubscribed
        self.isFree = isFree
        self.accessToken = accessToken
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case uuid
        case firstName = "first_name"
        case lastName = "last_name"
        case fullName = "full_name"
        case email
        case avatarUrl = "avatar_url"
        case timezone
        case countryCode = "country_code"
        case phone
        case emailVerifiedAt = "email_verified_at"
        case phoneVerifiedAt = "phone_verified_at"
        case subscriptionLevel = "subscription_level"
        case storeName = "store_name"
        case isProfileCompleted = "is_profile_completed"
        case isPackageSelected = "is_package_selected"
        case isPaymentMethods
        case isSubscribed = "is_subscribed"
        case isFree = "is_free"
        case accessToken = "access_token"
    }


}

